version: "3"
services:
  iyuuplus-dev:
    stdin_open: true
    tty: true
    environment:
      - IYUU_REPO_URL=https://github.com/CrytisMT/iyuuplus-dev.git
    volumes:
      - /root/iyuu:/iyuu
      - /root/data:/data
    ports:
      - "8780:8780"
    container_name: IYUUPlus
    restart: always
    image: iyuucn/iyuuplus-dev:latest
